# Numpy Crash Course

In [2]:
import numpy as np

In [5]:
np.__version__

'2.3.1'

In [ ]:
import sys  # checking system version
sys.version

'3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]'

# Creating Arrays

In [8]:
my_list=[0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [9]:
type(my_list)

list

In [10]:
arr=np.array(my_list)

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [20]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,3)

array([0, 1, 2])

In [ ]:
np.arange(20,10)  #1st arg < 2nd arg

array([], dtype=int64)

In [24]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [25]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [27]:
print(np.arange(30,20))
print(np.arange(-30,20))

[]
[-30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5
   6   7   8   9  10  11  12  13  14  15  16  17  18  19]


In [28]:
np.arange(10,10)

array([], dtype=int64)

In [30]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,50,5)  # start index = 10, stop index = 50, step = 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
np.arange(10,50,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3)  # parameter tunning  (float value)

array([0., 0., 0.])

In [ ]:
np.arange(5, dtype=int)  # hyperparamter tunning (int value)

array([0, 1, 2, 3, 4])

In [35]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [36]:
zero= np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [38]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros((10,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [41]:
np.zeros((5,10))   # here always 1st arg is represents ROW and 2nd is COLUMN

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n = (6,7)
n1 = (6,8)

print(np.zeros(n1))  # parameter tunnig
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [46]:
print(n)
print(n1)

(6, 7)
(6, 8)


In [ ]:
np.ones(3)  # print 1 (float value)

array([1., 1., 1.])

In [48]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [49]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
np.ones((5,4), dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.two()  # only print(zeros and ones)

AttributeError: module 'numpy' has no attribute 'two'

In [52]:
np.ones(2)

array([1., 1.])

In [53]:
np.ones((6,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [54]:
range(5)

range(0, 5)

In [58]:
r = range(5)
r

range(0, 5)

In [57]:
r= range(v)

NameError: name 'v' is not defined

In [59]:
for i in r:
    print(i)

0
1
2
3
4


In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
range(1,20)

range(1, 20)

In [62]:
list(range(1,20))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [63]:
list(range(1,20,5))

[1, 6, 11, 16]

In [65]:
y =list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [66]:
rand(3,2)

NameError: name 'rand' is not defined

In [67]:
random.rand(3,2)

NameError: name 'random' is not defined

In [68]:
np.random(3,2)

TypeError: 'module' object is not callable

In [69]:
np.rand(3,2)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(3,2)  # randomly creat values ( 3 row and 2 column)

array([[0.37307616, 0.63072519],
       [0.36067541, 0.95967067],
       [0.97113446, 0.85356531]])

In [ ]:
np.random.rand(5) # randomly creat 5 values 

array([0.67908674, 0.44333139, 0.44918936, 0.22309849, 0.96939093])

In [72]:
# how to print integer values

np.random.randint(4)

3

In [74]:
np.random.randint(2,4)

2

In [75]:
np.random.randint(0,1)

0

In [78]:
np.random.randint(10,20,5)

array([18, 18, 10, 10, 19], dtype=int32)

In [79]:
np.random.randint(1,6,4)

array([4, 3, 3, 1], dtype=int32)

In [80]:
np.random.rand(3)

array([0.83725205, 0.14604464, 0.536067  ])

In [81]:
np.random.randint(30,20,10)

ValueError: low >= high

In [82]:
np.random.randint(-30,20,5)

array([ -9,   3, -11,  18,   4], dtype=int32)

In [83]:
np.random.randint(20,30,5)

array([22, 28, 20, 28, 22], dtype=int32)

In [ ]:
np.random.randint(5,9)  # randomly get number between <=1 and >=5

5

In [85]:
np.random.randint(10,21,3)

array([19, 10, 16], dtype=int32)

In [87]:
np.random.randint(1,20,10)

array([17, 13,  5, 11,  2,  6, 11, 15, 16,  8], dtype=int32)

In [88]:
np.random.randint(10,40,(10,10))

array([[23, 25, 21, 29, 26, 36, 21, 14, 34, 17],
       [15, 32, 33, 26, 35, 27, 35, 21, 12, 39],
       [36, 16, 15, 19, 26, 36, 29, 22, 18, 26],
       [33, 24, 33, 24, 32, 29, 17, 22, 35, 22],
       [17, 35, 13, 28, 15, 23, 25, 22, 35, 38],
       [33, 30, 17, 17, 22, 35, 38, 29, 20, 11],
       [15, 10, 27, 32, 30, 15, 29, 25, 38, 16],
       [18, 12, 35, 20, 29, 37, 19, 37, 30, 15],
       [39, 20, 21, 17, 10, 14, 39, 39, 24, 30],
       [11, 16, 39, 21, 37, 37, 33, 15, 23, 38]], dtype=int32)

In [ ]:
np.random.randint(1,100,(12,12)) #generte the element 10 -30 with 4*4 mtri

array([[13,  4, 34, 48, 63, 56, 32,  2,  1, 34,  2, 41],
       [21, 67, 55, 71, 37, 14, 30, 84, 32,  7, 13, 68],
       [37, 64, 12, 14, 72, 24, 47, 53, 74,  1, 56, 42],
       [23, 92, 58, 67, 45, 90, 13, 20, 41, 11, 13, 77],
       [63, 41,  8, 88, 11, 87, 52, 21, 90, 10,  7, 24],
       [ 5, 31, 92, 30, 66, 30, 24, 83, 49, 44, 76, 41],
       [19, 78, 74, 12, 41, 63, 81, 74, 42, 60, 19, 96],
       [19, 67, 96, 93, 23, 40, 31, 88, 90, 19, 26, 46],
       [29, 85,  3, 86, 62, 54, 72, 26, 75, 87, 32, 74],
       [33, 78, 45, 50, 79, 74, 69, 25, 32, 44, 46, 69],
       [56, 34, 49, 67, 72, 86, 40, 82, 81, 29, 11, 78],
       [64, 57, 37, 30, 88, 22, 59, 15, 14, 61, 35, 42]], dtype=int32)

In [91]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [96]:
b =  np.random.randint(10,20,(5,4))
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [97]:
type (b)

numpy.ndarray

In [98]:
b[:]

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [ ]:
b[1:3]  # 1 row to 2 row  (3 = n-1)

array([[10, 12, 15, 17],
       [16, 14, 11, 19]], dtype=int32)

In [101]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [102]:
b[1,2]

np.int32(15)

In [103]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [106]:
b[1,-1]

np.int32(17)

In [107]:
b[2:3]

array([[16, 14, 11, 19]], dtype=int32)

In [108]:
b[0:-2]

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19]], dtype=int32)

In [109]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [110]:
b[0,2]

np.int32(18)

In [111]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [112]:
b[-5,-3]

np.int32(12)

In [113]:
b[-4,2]

np.int32(15)

In [115]:
np.random.randint(10,20,(4,4))

array([[17, 11, 10, 17],
       [15, 12, 18, 17],
       [17, 18, 12, 10],
       [14, 11, 11, 17]], dtype=int32)

In [116]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [117]:
b[-4,-2]

np.int32(15)

In [118]:
b

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

In [119]:
b[-4:2]

array([[10, 12, 15, 17]], dtype=int32)

In [120]:
b[:]

array([[10, 12, 18, 13],
       [10, 12, 15, 17],
       [16, 14, 11, 19],
       [11, 10, 13, 18],
       [19, 11, 11, 10]], dtype=int32)

## Operations

In [122]:
a = np.random.randint(10,20,10)
a

array([10, 19, 14, 15, 13, 12, 15, 17, 18, 11], dtype=int32)

In [123]:
id(a)

1909356739152

In [124]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [126]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [46, 58, 72, 60, 18, 73, 64,  5, 11,  1]], dtype=int32)

In [127]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [128]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6])

In [129]:
arr[:4]

array([0, 1, 2, 3])

In [130]:
arr2[:]

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [46, 58, 72, 60, 18, 73, 64,  5, 11,  1]], dtype=int32)

In [132]:
arr2[:4]

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83]], dtype=int32)

In [134]:
arr2[:5]

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24]], dtype=int32)

In [135]:
arr2[1,4]

np.int32(73)

In [136]:
arr2

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [46, 58, 72, 60, 18, 73, 64,  5, 11,  1]], dtype=int32)

In [137]:
arr2[-5,5]

np.int32(25)

In [138]:
arr2

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [46, 58, 72, 60, 18, 73, 64,  5, 11,  1]], dtype=int32)

In [139]:
arr2[-1,-2]

np.int32(11)

In [140]:
arr2

array([[88, 63, 29, 27, 26, 36, 80, 31, 80, 33],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [46, 58, 72, 60, 18, 73, 64,  5, 11,  1]], dtype=int32)

In [141]:
arr[::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [142]:
arr2[::-1]

array([[46, 58, 72, 60, 18, 73, 64,  5, 11,  1],
       [31,  0, 35, 82, 28, 69, 35, 27, 89, 78],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [27, 91, 98, 99, 57, 97, 18, 24, 93, 88],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [38, 12, 68, 68, 47, 94, 23, 88, 78, 24],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [91, 49, 10, 99,  3, 98,  1, 87, 11, 12],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63],
       [88, 63, 29, 27, 26, 36, 80, 31, 80, 33]], dtype=int32)

In [143]:
arr2[::-2]

array([[46, 58, 72, 60, 18, 73, 64,  5, 11,  1],
       [12, 80, 24, 72,  2, 64, 28, 64, 84, 57],
       [79, 20,  5, 22, 67, 25, 73, 33, 34,  6],
       [84,  8, 27, 29,  1, 55, 59, 40, 24, 83],
       [61, 61,  4, 53, 73, 87, 71, 71, 41, 63]], dtype=int32)

In [144]:
arr

array([0, 1, 2, 3, 4, 5, 6])

In [145]:
arr.max()

np.int64(6)

In [146]:
arr.min()

np.int64(0)

In [147]:
arr.mean()

np.float64(3.0)

In [148]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [153]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [160]:
arr=[0,1,2,3,4,5]

In [162]:
type(arr)

list

In [164]:
arr = np.array(arr)
arr

array([0, 1, 2, 3, 4, 5])

In [165]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [166]:
arr.rehape(6,1)

AttributeError: 'numpy.ndarray' object has no attribute 'rehape'

In [167]:
arr

array([0, 1, 2, 3, 4, 5])

In [168]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [169]:
arr

array([0, 1, 2, 3, 4, 5])

In [170]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [171]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [172]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [173]:
arr

array([0, 1, 2, 3, 4, 5])

In [174]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [176]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [177]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [179]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Indexing

In [181]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
row = 4
col = 5

In [185]:
print(col)
print(row)
print(mat)

5
4
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [186]:
mat[row,col]

np.int64(45)

In [187]:
mat[4,5]

np.int64(45)

In [188]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
col = 6

In [190]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat[:,col]  # column slicing

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [ ]:
mat[row,:]  # row slicing

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [197]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [198]:
row

4

In [199]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [203]:
mat[1,4]

np.int64(14)

In [204]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [207]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [210]:
mat[6,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [211]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [217]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [219]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[0,1]

np.int64(1)

In [222]:
mat[1,6]

np.int64(16)

In [223]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [224]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [227]:
mat[2:3,4:5]

array([[24]])

In [228]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

## Masking

In [ ]:
mat  # also we clled as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [232]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [233]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [234]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [235]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [236]:
mat[mat==50]

array([50])

# 1. Array Creation Functions

In [237]:
import numpy as np

In [239]:
# creat an array form a list

a= np.array([1,2,3])
print('Arry a:',a)
a

Arry a: [1 2 3]


array([1, 2, 3])

In [240]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [241]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [243]:
e = np.ones((2,3))
print('Arry e:',e)

Arry e: [[1. 1. 1.]
 [1. 1. 1.]]


In [244]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


# 2. Array Manipulation Functions

In [247]:
# Reshape an array

a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print('reshaped array is - ',reshaped)

reshaped array is -  [[1 2 3]]


In [248]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [249]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [250]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]
